services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    networks:
      - ga-network
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 200M
        reservations:
          cpus: '0.5'
          memory: 100M

  db:
    image: mysql:8.4.1
    container_name: ga-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ga
      MYSQL_USER: ga
      MYSQL_PASSWORD: ga
    ports:
      - 3306:3306
    volumes:
      - ga-dbdata:/var/lib/mysql
    networks:
      - ga-network

  seq:
    container_name: ga-seq
    image: datalust/seq:latest
    networks:
      - ga-network
    ports:
      - 5341:5341
      - 8090:80
    environment:
      ACCEPT_EULA: Y
    volumes:
      - seq-data:/data

  zipkin:
    container_name: ga-zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

networks:
  ga-network:

volumes:
  ga-dbdata:
  seq-data:

