name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: php artisan test

  docker:
    name: Push Image Docker
    runs-on: ubuntu-22.04
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Construção da imagem Docker
        uses: docker/build-push-action@vv6.6.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            wescleymatos/poc-ga:${{github.run_number}}
            wescleymatos/poc-ga:latest
